[package]
name = "remur"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"

[features]
default = ["cached-decode", "software-tlb"]
cached-decode = []
software-tlb = []

[dependencies]

[dev-dependencies]
criterion = "0.7"

[build-dependencies]
cc = "1.0"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[[bench]]
name = "isa_benchmark"
harness = false
